target 'Cinecor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for 'Cinecor'

end

# Required by RNFirebase
pod 'Firebase'
pod 'Firebase/Core'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

# RNFirebase
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/AppIndexing'
pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/Storage'

pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  # Add any other subspecs you want to use in your project
]
